=== athulnair02/austin-eats/back-end/schemas/1_recipe_schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "unsure what to put here",
    "title": "Recipe Instance",
    "description": "Records the details for a recipe instance.",
    "type": "object",
    "properties": {
        "id": {
            "description": "A unique identifier of a recipe",
            "type": "number",
            "minimum": 0
        },
        "name": {
            "description": "The name of the recipe",
            "type": "string",
            "minLength": 1
        },
        "summary": {
            "description": "Quick summary overview of the recipe",
            "type": "string"
        },
        "image": {
            "description": "Image URL showing the dish the recipe prepares",
            "type": "string"
        },
        "source": {
            "description": "Records the source the recipe is provided by",
            "type": "object",
            "properties": {
                "name": {
                    "description": "The name of the recipe's source",
                    "type": "string",
                    "minLength": 1
                },
                "url": {
                    "description": "URL of the recipe's source page",
                    "type": "string",
                    "minLength": 1
                },
                "credits": {
                    "description": "Short motto or author's name of the recipe's source",
                    "type": "string"
                }
            },
            "required": [
                "name",
                "url",
                "credits"
            ],
            "additionalProperties": false
        },
        "preparation_minutes": {
            "description": "How many minutes the dish takes to prepare",
            "type": "number",
            "minimum": -1
        },
        "cooking_minutes": {
            "description": "How many minutes the dish takes to cook",
            "type": "number",
            "minimum": -1
        },
        "ready_in_minutes": {
            "description": "How many minutes the dish takes from start to finish",
            "type": "number",
            "minimum": -1
        },
        "instructions_minutes": {
            "description": "How many minutes the dish takes from start to finish, based on instruction analysis",
            "type": "number",
            "minimum": -1
        },
        "servings": {
            "description": "How many servings the recipe yields",
            "type": "number",
            "minimum": 0
        },
        "labels": {
            "description": "Set of pre-defined labels the recipe/dish can or cannot be classified as",
            "type": "object",
            "properties": {
                "vegetarian": {
                    "description": "Whether the dish is vegetarian",
                    "type": "boolean"
                },
                "vegan": {
                    "description": "Whether the dish is vegan",
                    "type": "boolean"
                },
                "gluten_free": {
                    "description": "Whether the dish is gluten free",
                    "type": "boolean"
                },
                "dairy_free": {
                    "description": "Whether the dish is dairy free",
                    "type": "boolean"
                },
                "very_healthy": {
                    "description": "Whether the dish is very healthy",
                    "type": "boolean"
                },
                "cheap": {
                    "description": "Whether the dish is cheap",
                    "type": "boolean"
                },
                "very_popular": {
                    "description": "Whether the recipe is very popular online",
                    "type": "boolean"
                },
                "sustainable": {
                    "description": "Whether the recipe is sustainable for the environment",
                    "type": "boolean"
                }
            },
            "required": [
                "vegetarian",
                "vegan",
                "gluten_free",
                "dairy_free",
                "very_healthy",
                "cheap",
                "very_popular",
                "sustainable"
            ],
            "additionalProperties": false
        },
        "health_score": {
            "description": "Recipe health factor score from 0-100",
            "type": "number",
            "minimum": 0,
            "maximum": 100
        },
        "ingredients": {
            "type": "array",
            "items": {
                "description": "List of ingredients used in the recipe",
                "type": "object",
                "properties": {
                    "aisle": {
                        "description": "Comma-separated shopping aisle titles the ingredient can be located in",
                        "type": "string"
                    },
                    "name": {
                        "description": "Name of the ingredient",
                        "type": "string",
                        "minLength": 1
                    },
                    "name_clean": {
                        "description": "Alternative, usually generic title of the ingredient",
                        "type": "string",
                        "minLength": 1
                    },
                    "amount": {
                        "description": "Amount required of the ingredient for the recipe",
                        "type": "number",
                        "minimum": 0
                    },
                    "unit": {
                        "description": "Measurement unit to describe the amount needed of the ingredient",
                        "type": "string"
                    }
                },
                "required": [
                    "aisle",
                    "name",
                    "name_clean",
                    "amount",
                    "unit"
                ],
                "additionalProperties": false
            }
        },
        "nutrition": {
            "description": "Set of nutritional information components describing the recipe",
            "type": "object",
            "properties": {
                "nutrients": {
                    "type": "array",
                    "items": {
                        "description": "List of nutrients in the recipe",
                        "type": "object",
                        "properties": {
                            "name": {
                                "description": "Name of the nutrient",
                                "type": "string",
                                "minLength": 1
                            },
                            "amount": {
                                "description": "Amount of the nutrient present",
                                "type": "number",
                                "minimum": 0
                            },
                            "unit": {
                                "description": "Unit to describe the nutrient amount",
                                "type": "string",
                                "minLength": 1
                            },
                            "percent_daily": {
                                "description": "Daily percent intake of the nutrient present",
                                "type": "number",
                                "minimum": 0
                            }
                        },
                        "required": [
                            "name",
                            "amount",
                            "unit",
                            "percent_daily"
                        ],
                        "additionalProperties": false
                    },
                    "minItems": 7
                },
                "caloric_breakdown": {
                    "description": "Breakdown of where calories are allocated in the dish",
                    "type": "object",
                    "properties": {
                        "percent_protein": {
                            "description": "Percent of calories related to protein",
                            "type": "number",
                            "minimum": 0
                        },
                        "percent_fat": {
                            "description": "Percent of calories related to fats",
                            "type": "number",
                            "minimum": 0
                        },
                        "percent_carbs": {
                            "description": "Percent of calories related to carbohydrates",
                            "type": "number",
                            "minimum": 0
                        }
                    },
                    "required": [
                        "percent_protein",
                        "percent_fat",
                        "percent_carbs"
                    ],
                    "additionalProperties": false
                },
                "weight_per_serving": {
                    "description": "Weight information for each serving of the dish",
                    "type": "object",
                    "properties": {
                        "amount": {
                            "description": "Amount of weight per serving",
                            "type": "number",
                            "minimum": 0
                        },
                        "unit": {
                            "description": "Unit to describe the amount of weight per serving",
                            "type": "string",
                            "minLength": 1
                        }
                    },
                    "required": [
                        "amount",
                        "unit"
                    ],
                    "additionalProperties": false
                }
            },
            "required": [
                "nutrients",
                "caloric_breakdown",
                "weight_per_serving"
            ],
            "additionalProperties": false
        },
        "instructions": {
            "type": "array",
            "items": {
                "description": "List of instructions for the recipe",
                "type": "string"
            },
            "minItems": 1
        },
        "cuisines": {
            "type": "array",
            "items": {
                "description": "List of cuisines the recipe is related to",
                "type": "string"
            }
        },
        "dish_types": {
            "type": "array",
            "items": {
                "description": "List of tags related to the type of dish the recipe is",
                "type": "string"
            }
        }
    },
    "required": [
        "id",
        "name",
        "image",
        "preparation_minutes",
        "cooking_minutes",
        "ready_in_minutes",
        "instructions_minutes",
        "servings",
        "labels",
        "health_score",
        "ingredients",
        "nutrition",
        "instructions",
        "cuisines",
        "dish_types"
    ],
    "additionalProperties": false
}

=== athulnair02/austin-eats/front-end/src/temp-backend/recipes.json
[{
    "id": 0,
    "name": "Wuxi Ribs",
    "summary": "Wuxi Ribs is a <b>gluten free and dairy free</b> main course. One portion of this dish contains around <b>40g of protein</b>, <b>44g of fat</b>, and a total of <b>738 calories</b>. For <b>$3.79 per serving</b>, this recipe <b>covers 30%</b> of your daily requirements of vitamins and minerals. This recipe serves 3. 1 person were impressed by this recipe. It is brought to you by Foodista. Head to the store and pick up vinegar, pepper powder, soy sauce, and a few other things to make it today. From preparation to the plate, this recipe takes around <b>around 45 minutes</b>. With a spoonacular <b>score of 52%</b>, this dish is pretty good. Try <a href=\"https://spoonacular.com/recipes/dans-baby-back-ribs-you-can-make-tasty-ribs-599254\">Dan’s Baby Back Ribs – you can make tasty ribs</a>, <a href=\"https://spoonacular.com/recipes/sweet-temptation-ribs-tamarind-glazed-spare-ribs-391730\">Sweet Temptation Ribs: Tamarind-Glazed Spare Ribs</a>, and <a href=\"https://spoonacular.com/recipes/ward-winning-ribs-sticky-ribs-329399\">Ward Winning Ribs (Sticky Ribs)</a> for similar recipes.",
    "image": "https://spoonacular.com/recipeImages/665438-312x231.jpg",
    "source": {"name": "Foodista", "url": "https://www.foodista.com/recipe/CRPZZLRL/wuxi-ribs", "credits": "Foodista.com – The Cooking Encyclopedia Everyone Can Edit"},
    "preparation_minutes": -1,
    "cooking_minutes": -1,
    "ready_in_minutes": 45,
    "instructions_minutes": 122,
    "servings": 3,
    "labels": {
        "vegetarian": false,
        "vegan": false,
        "gluten_free": true,
        "dairy_free": true,
        "very_healthy": false,
        "cheap": false,
        "very_popular": false,
        "sustainable": false
    },
    "health_score": 16,
    "ingredients": [
        {
            "aisle": "Meat",
            "name": "pork ribs",
            "name_clean": "pork ribs",
            "amount": 800,
            "unit": "g"
        },
        {
            "aisle": "Produce",
            "name": "spring onions",
            "name_clean": "spring onions",
            "amount": 10,
            "unit": ""
        },
        {
            "aisle": "Produce;Ethnic Foods;Spices and Seasonings",
            "name": "ginger",
            "name_clean": "ginger",
            "amount": 4,
            "unit": "slices"
        },
        {
            "aisle": "Ethnic Foods;Condiments",
            "name": "soy sauce",
            "name_clean": "soy sauce",
            "amount": 2,
            "unit": "tablespoons"
        },
        {
            "aisle": "Alcoholic Beverages",
            "name": "rice wine",
            "name_clean": "shaoxing wine",
            "amount": 1,
            "unit": "cup"
        },
        {
            "aisle": "Ethnic Foods;Condiments",
            "name": "soy sauce",
            "name_clean": "soy sauce",
            "amount": 1,
            "unit": "cup"
        },
        {
            "aisle": "Oil, Vinegar, Salad Dressing",
            "name": "vinegar",
            "name_clean": "distilled white vinegar",
            "amount": 1,
            "unit": "tablespoon"
        },
        {
            "aisle": "Spices and Seasonings",
            "name": "star anise",
            "name_clean": "star anise",
            "amount": 1,
            "unit": ""
        },
        {
            "aisle": "Spices and Seasonings",
            "name": "clove",
            "name_clean": "clove",
            "amount": 1,
            "unit": ""
        },
        {
            "aisle": "Spices and Seasonings",
            "name": "red pepper powder",
            "name_clean": "ground cayenne pepper",
            "amount": 0.25,
            "unit": "teaspoon"
        },
        {
            "aisle": "Ethnic Foods;Spices and Seasonings",
            "name": "5 spice powder",
            "name_clean": "chinese five spice",
            "amount": 5,
            "unit": ""
        },
        {
            "aisle": "Condiments",
            "name": "ketchup",
            "name_clean": "ketchup",
            "amount": 1,
            "unit": "tablespoon"
        },
        {
            "aisle": "Baking",
            "name": "sugar",
            "name_clean": "sugar",
            "amount": 2,
            "unit": "tablespoons"
        }
    ],
    "nutrition": {
        "nutrients": [
            {"name": "Calories", "amount": 737.06, "unit": "kcal", "percent_daily": 36.85},
            {"name": "Fat", "amount": 44.25, "unit": "g", "percent_daily": 68.08},
            {"name": "Saturated Fat", "amount": 14.1, "unit": "g", "percent_daily": 88.14},
            {"name": "Carbohydrates", "amount": 22.86, "unit": "g", "percent_daily": 7.62},
            {"name": "Sugar", "amount": 11.57, "unit": "g", "percent_daily": 12.85},
            {"name": "Sodium", "amount": 5198.8, "unit": "mg", "percent_daily": 225.9},
            {"name": "Protein", "amount": 39.87, "unit": "g", "percent_daily": 79.75}
        ],
        "caloric_breakdown": {"percent_protein": 24.57, "percent_fat": 61.34, "percent_carbs": 14.09},
        "weight_per_serving": {"amount": 419, "unit": "g"}
    },
    "instructions": [
        "Marinade ribs with 2 tablespoons soy sauce, heat up 2 cups of oil in the wok with full gas power. Fry the ribs in 180C Oil for 2 minutes and place it on a plate. This procedure is for colouring the ribs.",
        "Heat up 1 tablespoon of oil and stir-fry the spring onion and , ginger until the fragrance comes out.",
        "Place the spring onion and ginger into a stock pot and place",
        "ribs on top of the spring onion.",
        "Add all the spice, Shaoshing rice wine, soy sauce and dark vinegar into the stock pot and use full gas power to boil everything at first. Once it has boiled turn reduce the temperate to the lowest gas heat and simmer for 1.5 hours.",
        "Add sugar and ketchup after the ribs have simmered for 1.5 hours and keep simmering until the meat on the ribs is soft.",
        "Time to make: 2 hours",
        "Serves: 3 people"
    ],
    "cuisines": ["American", "Chinese"],
    "dish_types": ["lunch", "dinner"]
},
{
    "id": 1,
    "name": "Spare Ribs",
    "summary": "If you have roughly <b>roughly 45 minutes</b> to spend in the kitchen, Spare Ribs might be a tremendous <b>gluten free and dairy free</b> recipe to try. For <b>$2.03 per serving</b>, this recipe <b>covers 23%</b> of your daily requirements of vitamins and minerals. This recipe serves 3. This main course has <b>773 calories</b>, <b>35g of protein</b>, and <b>59g of fat</b> per serving. 2 people were glad they tried this recipe. It is brought to you by Foodista. If you have spare ribs, hoisin sauce, soy sauce, and a few other ingredients on hand, you can make it. Taking all factors into account, this recipe <b>earns a spoonacular score of 51%</b>, which is solid. Try <a href=\"https://spoonacular.com/recipes/sweet-temptation-ribs-tamarind-glazed-spare-ribs-391730\">Sweet Temptation Ribs: Tamarind-Glazed Spare Ribs</a>, <a href=\"https://spoonacular.com/recipes/spare-ribs-83079\">Spare Ribs</a>, and <a href=\"https://spoonacular.com/recipes/dads-spare-ribs-288209\">Dad's Spare Ribs</a> for similar recipes.",
    "image": "https://spoonacular.com/recipeImages/660884-312x231.jpg",
    "source": {"name": "Foodista", "url": "https://www.foodista.com/recipe/M86P5G7L/spare-ribs", "credits": "Foodista.com – The Cooking Encyclopedia Everyone Can Edit"},
    "preparation_minutes": -1,
    "cooking_minutes": -1,
    "ready_in_minutes": 45,
    "instructions_minutes": 45,
    "servings": 3,
    "labels": {
        "vegetarian": false,
        "vegan": false,
        "gluten_free": true,
        "dairy_free": true,
        "very_healthy": false,
        "cheap": false,
        "very_popular": false,
        "sustainable": false
    },
    "health_score": 12,
    "ingredients": [
        {
            "aisle": "Oil, Vinegar, Salad Dressing",
            "name": "oil",
            "name_clean": "cooking oil",
            "amount": 2,
            "unit": "tablespoons"
        },
        {
            "aisle": "Nut butters, Jams, and Honey",
            "name": "clear honey",
            "name_clean": "honey",
            "amount": 3,
            "unit": "tablespoons"
        },
        {
            "aisle": "Produce;Ethnic Foods;Spices and Seasonings",
            "name": "fresh ginger root",
            "name_clean": "ginger",
            "amount": 1,
            "unit": "piece"
        },
        {
            "aisle": "Ethnic Foods;Condiments",
            "name": "soy sauce",
            "name_clean": "soy sauce",
            "amount": 2,
            "unit": "tablespoons"
        },
        {
            "aisle": "Ethnic Foods",
            "name": "hoisin sauce",
            "name_clean": "hoisin sauce",
            "amount": 2,
            "unit": "tablespoons"
        },
        {
            "aisle": "Ethnic Foods;Spices and Seasonings",
            "name": "5 spice powder",
            "name_clean": "chinese five spice",
            "amount": 1,
            "unit": "teaspoon"
        },
        {
            "aisle": "Produce",
            "name": "garlic cloves",
            "name_clean": "garlic",
            "amount": 2,
            "unit": ""
        },
        {
            "aisle": "Meat",
            "name": "spare ribs",
            "name_clean": "spare ribs",
            "amount": 2,
            "unit": "pounds"
        }
    ],
    "nutrition": {
        "nutrients": [
            {"name": "Calories", "amount": 772.7, "unit": "kcal", "percent_daily": 38.63},
            {"name": "Fat", "amount": 59.48, "unit": "g", "percent_daily": 91.51},
            {"name": "Saturated Fat", "amount": 16.7, "unit": "g", "percent_daily": 104.38},
            {"name": "Carbohydrates", "amount": 24.42, "unit": "g", "percent_daily": 8.14},
