=== athulnair02/austin-eats/back-end/schemas/all_cultures_schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "unsure what to put here",
    "title": "All Culture Instances",
    "description": "Lists the details for all culture instances.",
    "type": "array",
    "items": {
        "description": "Records the details for a culture instance.",
        "type": "object",
        "properties": {
            "id": {
                "description": "A unique identifier for a culture",
                "type": "number",
                "minimum": 0
            },
            "name": {
                "description": "The name for the country",
                "type": "string",
                "minLength": 1
            },
            "alpha2code": {
                "description": "The alpha2code for the country the culture represents",
                "type": "string",
                "minLength": 2,
                "maxLength": 2
            },
            "alpha3code": {
                "description": "The alpha3code for the country the culture represents",
                "type": "string",
                "minLength": 3,
                "maxLength": 3
            },
            "capital": {
                "description": "The capital city for the country",
                "type": "string",
                "minLength": 1
            },
            "flags": {
                "description": "Various image formats for the country flag",
                "type": "object",
                "properties": {
                    "svg": {
                        "description": "SVG image URL for the country flag",
                        "type": "string"
                    },
                    "png": {
                        "description": "PNG image URL for the country flag",
                        "type": "string"
                    }
                }
            },
            "currencies": {
                "type": "array",
                "items": {
                    "description": "Set of currencies used in the country",
                    "type": "object",
                    "properties": {
                        "code": {
                            "description": "Shorthand currency code",
                            "type": "string",
                            "minLength": 1
                        },
                        "name": {
                            "description": "Name of the currency",
                            "type": "string",
                            "minLength": 1
                        },
                        "symbol": {
                            "description": "Symbol text ASCII of the currency",
                            "type": "string",
                            "minLength": 1,
                            "maxLength": 1
                        }
                    },
                    "required": [
                        "code",
                        "name"
                    ],
                    "additionalProperties": false
                }
            },
            "languages": {
                "type": "array",
                "items": {
                    "description": "Languages spoken in the country",
                    "type": "string"
                },
                "minItems": 1,
                "uniqueItems": true
            },
            "subregion": {
                "description": "Subregion of the country",
                "type": "string"
            },
            "region": {
                "description": "Region of the country",
                "type": "string",
                "minLength": 1
            },
            "population": {
                "description": "Population of the country",
                "type": "number",
                "minimum": 0
            },
            "latlng": {
                "type": "array",
                "items": {
                    "description": "Latitude and Longitude of the country",
                    "type": "number",
                    "minimum": -180,
                    "maximum": 180
                },
                "minItems": 2,
                "maxItems": 2
            },
            "demonym": {
                "description": "Demonym of the country",
                "type": "string",
                "minLength": 1
            },
            "regional_blocs": {
                "type": "array",
                "items": {
                    "description": "The regional blocs the country is involved in",
                    "type": "object",
                    "properties": {
                        "acronym": {
                            "description": "Commonly-known acronym for the regional bloc's name",
                            "type": "string"
                        },
                        "name" : {
                            "description": "Name of the regional bloc",
                            "type": "string",
                            "minLength": 1
                        }
                    },
                    "required": [
                        "name"
                    ],
                    "additionalProperties": false
                },
                "uniqueItems": true
            },
            "independent": {
                "type": "boolean",
                "description": "Whether the country is independent or dependent"
            },
            "summary": {
                "description": "Quick short summary describing the country",
                "type": "string",
                "minLength": 1
            }
        },
        "required": [
            "id",
            "name",
            "alpha2code",
            "alpha3code",
            "capital",
            "flags",
            "currencies",
            "languages",
            "subregion",
            "region",
            "population",
            "latlng",
            "demonym",
            "independent",
            "summary"
        ],
        "additionalProperties": false
    }
}

=== athulnair02/austin-eats/front-end/src/temp-backend/cultures.json
[{
    "id": 0,
    "name": "United States of America",
    "alpha2code": "US",
    "alpha3code": "USA",
    "capital": "Washington, D.C.",
    "flags": {"svg":"https://flagcdn.com/us.svg", "png":"https://flagcdn.com/w320/us.png"},
    "currencies": [{"code":"USD", "name":"United States dollar", "symbol":"$"}],
    "languages": ["English"],
    "subregion": "Northern America",
    "region": "Americas",
    "population": 329484123,
    "latlng": [38.0,-97.0],
    "demonym": "American",
    "regional_blocs": [{"acronym":"NAFTA", "name":"North American Free Trade Agreement"}],
    "independent": true,
    "summary": "The United States of America, commonly known as the United States or America, is a transcontinental country located primarily in North America. It consists of 50 states, a federal district, five major unincorporated territories, nine minor outlying islands, and 326 Indian reservations. It is either the fourth- or third-largest country by land or total area, respectively. The United States shares land borders with Canada to its north and with Mexico to its south. It has maritime borders with the Bahamas, Cuba, Russia, and other nations. With a population of over 331 million, it is the third most populous country in the world. The national capital is Washington, D.C., and the most populous city and financial center is New York City."
},
{
    "id": 1,
    "name": "Mexico",
    "alpha2code": "MX",
    "alpha3code": "MEX",
    "capital": "Mexico City",
    "flags": {"svg":"https://flagcdn.com/mx.svg", "png":"https://flagcdn.com/w320/mx.png"},
    "currencies": [{"code":"MXN", "name":"Mexican peso", "symbol":"$"}],
    "languages": ["Spanish"],
    "subregion": "North America",
    "region": "Americas",
    "population": 128932753,
    "latlng": [23.0,-102.0],
    "demonym": "Mexican",
    "regional_blocs": [{"acronym":"PA", "name":"Pacific Alliance"}, {"acronym":"NAFTA", "name":"North American Free Trade Agreement"}],
    "independent": true,
    "summary": "Mexico, officially the United Mexican States, is a country in the southern portion of North America. It is bordered to the north by the United States; to the south and west by the Pacific Ocean; to the southeast by Guatemala, Belize, and the Caribbean Sea; and to the east by the Gulf of Mexico. Mexico covers 1,972,550 square kilometers (761,610 sq mi), making it the world's 13th-largest country by area; with approximately 126,014,024 inhabitants, it is the 10th-most-populous country and has the most Spanish-speakers. Mexico is organized as a federal republic comprising 31 states and Mexico City, its capital. Other major urban areas include Monterrey, Guadalajara, Puebla, Toluca, Tijuana, Ciudad Juárez, and León."
},
{
    "id": 2,
    "name": "Japan",
    "alpha2code": "JP",
    "alpha3code": "JPN",
    "capital": "Tokyo",
    "flags": {"svg":"https://flagcdn.com/jp.svg", "png":"https://flagcdn.com/w320/jp.png"},
    "currencies": [{"code":"JPY", "name":"Japanese yen", "symbol":"¥"}],
    "languages": ["Japanese"],
    "subregion": "Eastern Asia",
    "region": "Asia",
    "population": 125836021,
    "latlng": [36.0,138.0],
    "demonym": "Japanese",
    "independent": true,
    "summary": "Japan is an island country in East Asia. It is situated in the northwest Pacific Ocean, and is bordered on the west by the Sea of Japan, while extending from the Sea of Okhotsk in the north toward the East China Sea, Philippine Sea, and Taiwan in the south. Japan is a part of the Ring of Fire, and spans an archipelago of 6852 islands covering 377,975 square kilometers (145,937 sq mi); the five main islands are Hokkaido, Honshu, Shikoku, Kyushu, and Okinawa. Tokyo is the nation's capital and largest city, followed by Yokohama, Osaka, Nagoya, Sapporo, Fukuoka, Kobe, and Kyoto."
}]
